### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by yasushisakai** [AndresRicoM/Jett-Sen#6]
is this a parsing error??
```
unsupervised.py:54: RuntimeWarning: invalid value encountered in true_divide
  speed = ((speed - np.amin(speed)) / (np.amax(speed) - np.amin(speed)))
Traceback (most recent call last):
  File "unsupervised.py", line 96, in <module>
    kmeans.fit(X)
  File "/home/yasushi/.pyenv/versions/pana-mapping/lib/python3.7/site-packages/sklearn/cluster/k_means_.py", line 972, in fit
    return_n_iter=True)
  File "/home/yasushi/.pyenv/versions/pana-mapping/lib/python3.7/site-packages/sklearn/cluster/k_means_.py", line 312, in k_means
    order=order, copy=copy_x)
  File "/home/yasushi/.pyenv/versions/pana-mapping/lib/python3.7/site-packages/sklearn/utils/validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home/yasushi/.pyenv/versions/pana-mapping/lib/python3.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by AndresRicoM** [comment]
Very strange. It might be because its raising the error until it tries to normalize the speed data. Are you running it on the files generated by clean?

**Comment by yasushisakai** [comment]
yes, I've changed to `index to -1` obeying the comment and then ran normally.
indexies when pasing somehow changes....
